### ISSUE TITLE
Selecting earthquakes to show by the geographical position of the epicenter

### ISSUE THREAD

**Issue by djozinovi** [INGV/shakemap4-web#23]
The following issue was originally opened via email by Alberto M. and Valentino L.

> In this case, my idea is to filter the events using the script “updateEventList.py”. 
> We can set the constraints (bounding box, point and radius, mag threshold, ecc….) in this file so we can deploy more than one website but with different settings.
> 
> An idea could to define an external file (es. “env_publish.py”) that can be included into “updateEventList.py” to specify the constraints params.

> would it be possible to insert an area like a simple rectangular area privided the two certices (latmin, lonmin), (latmax, lonmax) do delimit those shakemaps we want to include in the website ? 
> This would allow to have just one shakemap installation  at global scale but, for instance, expose on one site only those within Italy. I have looked at the code today and it should not be difficult to remove those events outside the selected area form the event list.

**Comment by vlauciani** [comment]
Hi Dario

I saw your code:
- https://github.com/INGV/shakemap4-web/blob/develop/updateEventList.py#L95

is there a way “include” an external file into “updateEventList.py” file?

The idea could be:
1) set default value into "updateEventList.py":
```
    minLat = -90
    maxLat = +90
    minLon = -180
    maxLon = +180
```
2) create an external file, for example, “bbox.txt” with:
```
    minLat = 36.0
    maxLat = 48.0
    minLon = 6.0
    maxLon = 20.0
```
and It, if exists, should override the default value.

Is it possibile?

Thank you,
Valentino

**Comment by amichelini** [comment]
yes, what presented by Valentino should be the proper way to do it at least for now. In the future there may be introduced more sophisticated ways to do it (e.g., polygons)
