### ISSUE TITLE
New Feature: Adding Metadata tab

### ISSUE THREAD

**Issue by SMIP-CGS** [INGV/shakemap4-web#27]
Adding a Metadata tab on the static page similar to what USGS has on its shakemap page would also be a useful feature.
 
Here is an example:
https://earthquake.usgs.gov/earthquakes/eventpage/us70009cel/shakemap/metadata

-Lijam

**Comment by djozinovi** [comment]
@SMIP-CGS There is now the Metadata page, accessed from the Leaflet view page. It is however different from the USGS implementation as they have chosen only some information from the Metadata file and the features they show are coded separately for each line of the Metadata tab they have. As here we were thinking of making something general (so not to pick just some specific features) I wrote the code which writes out all key-value pairs from the Metadata file. It makes the page a lot less pretty than the USGS page, but on the other hand it has all the information from the Metadata file.
