### ISSUE TITLE
mobile - Check visualisation on mobile browser

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#37]
Hi @serioca 

Looking the public site from mobile phone:
- http://shakemap.ingv.it/shake4/

the site is not correctly formatted; could you check the style?

![IMG_3671](https://user-images.githubusercontent.com/16477095/97539316-09945d00-19c2-11eb-89b2-3aa8159629f0.jpeg)
![IMG_3672](https://user-images.githubusercontent.com/16477095/97539323-0b5e2080-19c2-11eb-90d2-58512b3d274f.jpeg)

Thank you

**Comment by serioca** [comment]
**At first I applied the following modifications to the project structure:**

The file header.js is not used anymore, in favor of the file ./inc/header.html. 
header.html contains: Logo, navigation menu bar and banner_lista_terremoti.jpg
header.html is loaded by the function include_header, that is inside the file elaborate_config.js
The functions shared by all pages reside in the file elaborate_config.js, as it was already loaded by all of them

**Logo image**
The logo Image is now managed as not to be wider than the screen. 
See apropos the function: loadLogoImage  in  the file elaborate_config.js

**Events Table**
to make It Responsive, some code has been added to the file style.css

**Navigation menu bar**
to make It Responsive, some code has been added to the file style.css and some modification has been applied to the html (header.html), and elaborate_config.js (function toggle_menu_header)

The branch develop_sergio has been rebased onto the branch develop and then those modifications has been pushed to develop_sergio. No pull request has be made yet.
