### ISSUE TITLE
updateEventList.py - Remove an event from the list

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#38]
Hi @djozinovi 

I think could be a good idea to add an option to remove an event from the list and all files generated; this is useful when we decide to remove an event directory.

For example: `updateEventList.py --delete=<eventid>`

This command should remove the data from `events.js` and all create file in _eventid_ directory (**if it exists!**).
What do you think about?

Valentino

**Comment by djozinovi** [comment]
@vlauciani Is it working ok? Can I close the issue?

**Comment by vlauciani** [comment]
I tested It one time. Yes, close the issue and in case of problem I'll open it again.

Thank you.
