### ISSUE TITLE
INFORMATION (Disclaimer) 

### ISSUE THREAD

**Issue by amichelini** [INGV/shakemap4-web#4]
Now this page of the portal gives error (404 Not Found) and it should instead report the same disclaimer pages we already have for the previous version (<http://shakemap.rm.ingv.it/shake/disclaimer.html>)

**Comment by vlauciani** [comment]
@amichelini testing the page, it works:
![Screenshot 2020-01-15 at 14 37 53](https://user-images.githubusercontent.com/16477095/72438240-b3448d80-37a4-11ea-94f3-9f7b93b65d15.png)
is it ok?

**Comment by vlauciani** [comment]
Disclaimer issue is: https://github.com/INGV/shakemap4-web/issues/55
