### ISSUE TITLE
Shakemapeu: disclaimer, banner and footer

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#45]
@djozinovi can you work the GitLab issue:
- https://gitlab.rm.ingv.it/shakemap/shakemap4/-/issues/11

please, put the images into "images" folder and remove It from root project.

Thank you,
Valentino

**Comment by djozinovi** [comment]
@vlauciani The part of the lower right message has been fixed.

OK, I will make an image folder.

Regarding the images for ShakeMapEU: how do you change them? Just login to shakemapeu server using the info described [here](https://gitlab.rm.ingv.it/shakemap/shakemap4/-/issues/9) and change or there is another procedure to do it?

**Comment by vlauciani** [comment]
Hi @djozinovi 

The "images" folder already exists; put there the images.

Regarding the way to change the images, I was thinking to use the concept adopted from Sergio; the `config.js` that starts from (https://github.com/INGV/shakemap4-web/blob/develop/config-example.js).

Could it be a solution?

**Comment by djozinovi** [comment]
@vlauciani Yes, it is already done for all the images except the banner above the table at the homepage. My question was about the ShakeMapEU: the images there are different from the ones we use in INGV version (see develop website). So how do we replace the images for the EU version? 
Also for the EU version only the index page should have the logos of the institutions at the top and the other pages should have the 'standard' top image (the analog seismogram). I sent you also an email on 4/11 about this.

**Comment by amichelini** [comment]
@djozinovi Yes, in the shakemapeu version you should put also the same banner (and footer when applicable) of the home page using the images i provided.

**Comment by djozinovi** [comment]
@vlauciani The images of the web-app are now in the images folder. For the EU version the images in the folder should be changed on the ShakeMapEU server.

@amichelini Should the banner be in all the pages or just the homepage? If just on the homepage what banner should be used for the other pages?

**Comment by amichelini** [comment]
@djozinovi 
> Should the banner be in all the pages or just the homepage? If just on the homepage what banner should be used for the other pages?

The banner that includes the RISE and SERA projects logo  should be in alla pages  replacing the drum seismograph.

The "home" page should have fewer events (the last five) to leave room for the  footer so that it appears when accessing the page.

The footer should also go in all the other pages just above the "Website Version: ....". Please also see the same post on gitlab "https://gitlab.rm.ingv.it/shakemap/shakemap4/-/issues/11"

**Comment by vlauciani** [comment]
The banner option was set into `config.js` file and @serioca is working in disclaimer too. https://github.com/INGV/shakemap4-web/issues/55
