### ISSUE TITLE
In INFORMATION to be added

### ISSUE THREAD

**Issue by amichelini** [INGV/shakemap4-web#5]
The INFORMATION should also provide information on *Related Links* and  *Scientific Background*.  

For the  *Related Links*:
- link to the USGS ShakeMap page
- link to all the European Shakemap providers as listed in the article we just published

For the *Scientific Background*, I would refer to general ShakeMap description (see the USGS site) and to the details of our new implementation as form the article  

We need to meet and decide on what to put in.

**Comment by vlauciani** [comment]
@amichelini is this issue completed? If yes, you can close it.

**Comment by amichelini** [comment]
This issue can be closed
