### ISSUE TITLE
Set disclaimer to use into 'config.js' file

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#55]
Hi @serioca 

To publish different *disclaimer* for different site, I created this two files (develop branch):
- `inc/disclaimer1.html`
- `inc/disclaimer2.html`

the idea is to set the filename into `config.js`, for example:
```
. . .
    disclaimer: {
	show: true,
	file: 'inc/disclaimer1.html',
    }
. . .
```

end "include" that file into the `index.html` file, here:
- https://github.com/INGV/shakemap4-web/blob/master/index.html#L31

Valentino

**Comment by serioca** [comment]
see PR #59
