### ISSUE TITLE
Events list layout difference between 'Home' and 'Archive'

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#58]
Dear @serioca 

I noticed a layout difference between Home page and Archive page; please check the images below.

<img width="1503" alt="Screenshot 2020-11-19 at 14 25 59" src="https://user-images.githubusercontent.com/16477095/99672226-67710d80-2a73-11eb-884e-d47061b43a3b.png">
<img width="1503" alt="Screenshot 2020-11-19 at 14 26 04" src="https://user-images.githubusercontent.com/16477095/99672232-69d36780-2a73-11eb-9fb0-616f685332ba.png">

Could you check it?

Thank you.

**Comment by serioca** [comment]
I'm not able to reproduce this problem in any of the available links (production and development)
Also I see that the banner image  in the example is truncated along the height, but in the same way in the two pages,  home and archive.
I'm confused ...

**Comment by vlauciani** [comment]
Hi @serioca 

No, the problem is not the banner image (I apologise), events list!
As you can see, the two lists have different format style.

**Comment by serioca** [comment]
see  #60
