### ISSUE TITLE
Home page and Archive list pages fixes

### ISSUE THREAD

**Issue by amichelini** [INGV/shakemap4-web#6]
### Some fixing 
The following lists some fixing absolutely required for the lists presented in the `HOME` and `ARCHIVE` pages.  

The   [Home page](http://shakemap4-dev.int.ingv.it:8091) should

1.  list all the most recent events. I find that I am unable to obtain an updated list of the events. In practice, it is updated only until January 7th (see picture)
![Screen Shot 2020-01-27 at 5 12 16 PM](https://user-images.githubusercontent.com/2528301/73191843-72dffa80-4128-11ea-8a63-2fe6689b78db.png)

2. The Time heading  should be `Time (HH:MM)` 

3. The Time column values should always include 2 digits for Hour and 2 for Minute (e.g. 06:05 and not 6:5)

4. The Magnitude column should be always with 1 decimal digit (e.g., 3.0 and not just 3)

5. In the  [Archive page](http://shakemap4-dev.int.ingv.it:8091/archive.html), I do not understand why today (Jan 27 at 16:32 UTC) the list of earthquakes does not include the latest events (i.e., 23824191, 23824051, 23822621, 23820881, 23814821) that had shakemaps calculated (see picture)
![Screen Shot 2020-01-27 at 5 38 38 PM](https://user-images.githubusercontent.com/2528301/73194107-f0f1d080-412b-11ea-983b-0413687ffcd8.png)

**Comment by djozinovi** [comment]
The point number 5 happened because those events were not in the _events.js_ file, which should be generated by _updateEventList.py_ after a new event has been generated by ShakeMap.
But is the procedure set up so that _updateEventList.py_ runs automatically after ShakeMap has been run? @vlauciani

**Comment by vlauciani** [comment]
Hi @djozinovi 

Yes, the script `updateEventList.py` is running every minutes; this is the log with some errors:
```
Processing event:23625961
Processing event:23807691
Processing event:23791601
Processing event:23820881
Processing event:23665211
Processing event:23763561
Processing event:23824051
Processing event:23749771
Processing event:23614031
 No intensity overlay file for event:23614031
Processing event:23605521
 No intensity overlay file for event:23605521
Processing event:23624391
Processing event:23814821
Traceback (most recent call last):
  File "/var/www/updateEventList.py", line 94, in <module>
    final_list.append(get_parameters(event))
  File "/var/www/updateEventList.py", line 56, in get_parameters
    with open(info_file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/23814821/current/products/info.json'
```

**Comment by Fran89** [comment]
It's the Javascript Date function.

You have to subtract 1 from the month because in javascript months start at 0.

Note: JavaScript counts months from 0 to 11.

January is 0. December is 11.

I changed it to:

```
var events = events.map(function (o) {
  o.date = new Date(o.year, Number(o.month-1), o.day, o.hour, o.minute, o.second, 0);
  return o;
});
```

I'd make a pull request but I'm still setting up some git stuff.

Thanks for making this available by the way!

**Comment by vlauciani** [comment]
Hi @Fran89 

Thank you very much for your investigation and solution.
Fell free to submit PR ;-)

I'll fix the function with your suggestion.

Valentino
