### ISSUE TITLE
Products Download page

### ISSUE THREAD

**Issue by amichelini** [INGV/shakemap4-web#7]
We need to have the web page where to download all what produced (i.e., the equivalent of the download page of the old version of shakemap)

**Comment by vlauciani** [comment]
The pull was done on server; test it and close issue if it works.

**Comment by amichelini** [comment]
Unfortunately, it does not work. It appears the download button and my expectation is that it opens a page with the different products to be downloaded separately.   
@dario I imagine that you are still working on it (?)

**Comment by vlauciani** [comment]
@amichelini and @djozinovi 

I've added a `crontab` line to automatically `pull` (every 5min) this project on our server; then, you check your update directly.

**Comment by djozinovi** [comment]
@amichelini For me it works, when I click on the 'download products' button it takes me to the page to download the products: 
![image](https://user-images.githubusercontent.com/38222535/74755034-d0242300-5272-11ea-977d-2a4cafa253bc.png)

**Comment by amichelini** [comment]
Ciao @Dario, I have no doubts that works for you but it does not seem to work on the site that has been set up by Valentino (see http://shakemap4-dev.int.ingv.it:8091/viewLeaflet.html?eventid=23967941).   
I am afraid that there is something missing.

**Comment by vlauciani** [comment]
Hi @amichelini 

It works also for me; could it be a browser cache problem? Did you try to change browser (or empty the cache)?

**Comment by djozinovi** [comment]
@amichelini @vlauciani For me it works also on the site that has been set up by Valentino (see the address in the image I sent 2 messages ago), so this looks like a cache problem.

**Comment by amichelini** [comment]
yes I have tried with firefox and it works!
Thanks

**Comment by amichelini** [comment]
There are missing a number of things:
1) the shape files in ESRI format.
2) all the jpg of the static maps

**Comment by amichelini** [comment]
The download page should be organized as follows:     

**- Peak Ground Motion Maps**
*-- PNG*
--- `intensity.png`  
--- `pga.png`  
--- `pgv.png`  
--- `psa0p3.png`
--- `psa1p0.png`
--- `psa3p0.png`
*-- PDF*
--- `intensity.pdf` 
--- `pga.pdf`   
--- `pgv.pdf`   
--- `psa0p3.pdf`
--- `psa1p0.pdf` 
--- `psa3p0.pdf`   

**- Contours and shape files**
-- `cont_mi.json`   
-- `cont_pga.json`   
-- `cont_pgv.json`  
-- `cont_psa0p3.json`   
-- `cont_psa1p0.json`  
-- `cont_psa3p0.json`  
-- `shape.zip`   

**- Rasters and grid**
-- `raster.zip`  
-- `grid.xml`  
-- `intensity_overlay.png`   
-- `uncertainty.xml`  

**- Regressions**
-- `mmi_regr.png` 
-- `pga_regr.png`  
-- `pgv_regr.png`  
-- `psa0p3_regr.png`
-- `psa1p0_regr.png`
-- `psa3p0_regr.png`  

**- Other files**
-- `attenuation_curves.json`
-- `stationlist.json`  
-- `info.json`  
-- `rupture.json`  
-- `shake_result.hdf`

**Comment by amichelini** [comment]
@djozinovi 

The banner is fine and you can proceed to change it to all the other pages
