### ISSUE TITLE
Separate page for historic events

### ISSUE THREAD

**Issue by djozinovi** [INGV/shakemap4-web#79]
A new archive page should be created for historic events specifically. It should have the same look and functions as the archive page. It should be accessible from the INFORMATION menu.

**Comment by LiciaFaenza** [comment]
Add graphs in ANALYSIS VIEW and also stations (macro points) in STATION LIST

**Comment by djozinovi** [comment]
Issue fixed with commit a7560ba1cfdfb02a0bbc50abafbbb37094f133f9
