### ISSUE TITLE
double view problem

### ISSUE THREAD

**Issue by amichelini** [INGV/shakemap4-web#9]
I just found out that when displaying  using the double view option there is a little  problem.   
The earthquake I have been looking at is http://shakemap4-dev.int.ingv.it:8091/viewLeaflet2.html?eventid=24317311   

In practice,  in double view, the right panel does not include the stations and they cannot be included since missing in the pull down menu.

**Comment by djozinovi** [comment]
@amichelini Yes, this was by design, that the stations and the fault is only visible in the left panel. But I can't remember why we did it. I will put also the station and fault option in the right panel.
